name: Deploy BrainPlay

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Go to project folder
        run: cd ~/brainplay

      - name: Pull latest code
        run: |
          cd ~/brainplay
          git pull origin main

      - name: Install dependencies
        run: |
          cd ~/brainplay
          npm install